### ISSUE TITLE
Neprocházející test 21

### ISSUE THREAD

**Issue by Honza-Bota** [3DprintFIT/B232HW-Assignment#1]
Test 21 mi jako jediný neprochází na 100 %. Při porovnání obrázku je moje řešení oproti referenčnímu odlišné o 5 pixelů. 
Co s tím mám prosím dělat? Prochází mi na cca 99.993 %.

![image](https://github.com/3DprintFIT/B232HW-Assignment/assets/45333163/539afe33-6b74-44b3-8bb2-48185d788a3e)
@hroncok @syky27

**Comment by syky27** [comment]
Za me to je v pohode, nemusis se s tim trapit.

**Comment by hroncok** [comment]
Připomínám, že similarity score není jednoznačný ukazatel správnosti. Pokud je 1.0, obrázky jsou totožné. Pokud ale není 1.0, neznamená to, že je to špatně -- pouze, že je potřeba provést kontrolu okem.
